site_name: CIRRUS Admin Documentation
site_url: https://jira.ucar.edu/secure/RapidBoard.jspa?rapidView=220&projectKey=CCPP
site_description: Documentation for CIRRUS Admins
repo_url: https://github.com/NCAR/cirrus-admin-docs/tree/main/docs
nav:
  - Home: index.md
  - About: overview/about.md
  - Use Cases: overview/use-cases.md
  - Availability:
    - Architecture: overview/architecture.md
  - How-Tos: 
      - Agile Interaction: how-to/agile.md            
      - Argo CD:
        - Deploy Applications: how-to/argocd/deploy.md
        - Update Applications: how-to/argocd/update.md
      - Documentation Site Build: how-to/docs/build-docs.md
      - Encryption: how-to/encryption/sops-age.md
      - GitHub Actions:
        - Setup GitHub Action to Build and Push Docker Image: how-to/GitHub/gha-docker-build.md
      - Harbor:
        - Add Users: how-to/harbor/add-users.md
      - Kubernetes (k8s) JupyterHub:
        - Customize Jupyter Docker Image: how-to/k8sJH/customize-docker.md
      - Stratus:
        - Add User: how-to/stratus/add_user.md
  - SLA's:
      - CIRRUS: slas/slas.md
      - GLADE & Stratus: https://ncar-hpc-docs-arc-iframe.readthedocs.io/storage-systems/glade/?h=glade#glade-file-spaces
theme: 
  name: readthedocs
  logo: 'images/NSF-NCAR-UCAR-Light.png'
extra_css:
  - "css/extra.css"
extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.js
  - js/extra.js