# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the docs directory and image
# Set the workflow name
name: Build docs image

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the docs/ path
on:
  push:
    paths:
      - docs/**
      - Dockerfile

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  build-docs-image:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: ubuntu-latest
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the repo
        uses: actions/checkout@v3
      # Step 2 is to login to docker hub so the image can be pushed
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        # GitHub secrets are used to provide login information to docker hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      # Build and push the image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          # Provide the current directory as build context 
          context: .
          # Specify where the Dockerfile is located in relation to the repo base path
          file: Dockerfile
          # Enable the push to docker hub
          push: true
          # Provide the tags to apply to the image, this example uses the latest image tag 
          tags: cislcloudpilot/admin-docs:${{ steps.date.outputs.date }}